// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Aspire.PostgreSQLSample.MigrationEntry.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Aspire.PostgreSQLSample.MigrationEntry.Entities.Configurations
{
    public partial class UserConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> entity)
        {
            entity.HasKey(e => e.Id).HasName("pk_users");

            entity.ToTable("users", "dbo");

            entity.HasIndex(e => e.Username, "idx_users_username").IsUnique();

            entity.Property(e => e.Id)
                .HasMaxLength(16)
                .HasComment("識別碼")
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("創建時間")
                .HasColumnName("created_at");
            entity.Property(e => e.Password)
                .HasMaxLength(255)
                .HasComment("密碼")
                .HasColumnName("password");
            entity.Property(e => e.State)
                .HasDefaultValue(0)
                .HasComment("狀態")
                .HasColumnName("state");
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("更新時間")
                .HasColumnName("update_at");
            entity.Property(e => e.Username)
                .HasMaxLength(32)
                .HasComment("用戶名")
                .HasColumnName("username");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<User> entity);
    }
}
